[package]
name = "pike"
version = "0.1.0"
authors = ["rzvxa <rzvxa@protonmail.com>"]
description = "A macro collection to pipe |> your functions calls, like in F# or Elixir."
edition = "2021"
keywords = ["pike", "pipe", "function", "elixir", "macro", "composition"]
license = "MIR OR Apache-2.0"
